/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorThemeRouteImport } from './routes/editor.theme'
import { Route as ApiGoogleFontsRouteImport } from './routes/api.google-fonts'
import { Route as ApiGenerateThemeRouteImport } from './routes/api.generate-theme'
import { Route as ApiFrontendLibThemeRouteImport } from './routes/api.frontend-lib.theme'

const EditorThemeRoute = EditorThemeRouteImport.update({
  id: '/editor/theme',
  path: '/editor/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleFontsRoute = ApiGoogleFontsRouteImport.update({
  id: '/api/google-fonts',
  path: '/api/google-fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateThemeRoute = ApiGenerateThemeRouteImport.update({
  id: '/api/generate-theme',
  path: '/api/generate-theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrontendLibThemeRoute = ApiFrontendLibThemeRouteImport.update({
  id: '/api/frontend-lib/theme',
  path: '/api/frontend-lib/theme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/generate-theme': typeof ApiGenerateThemeRoute
  '/api/google-fonts': typeof ApiGoogleFontsRoute
  '/editor/theme': typeof EditorThemeRoute
  '/api/frontend-lib/theme': typeof ApiFrontendLibThemeRoute
}
export interface FileRoutesByTo {
  '/api/generate-theme': typeof ApiGenerateThemeRoute
  '/api/google-fonts': typeof ApiGoogleFontsRoute
  '/editor/theme': typeof EditorThemeRoute
  '/api/frontend-lib/theme': typeof ApiFrontendLibThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/generate-theme': typeof ApiGenerateThemeRoute
  '/api/google-fonts': typeof ApiGoogleFontsRoute
  '/editor/theme': typeof EditorThemeRoute
  '/api/frontend-lib/theme': typeof ApiFrontendLibThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/generate-theme'
    | '/api/google-fonts'
    | '/editor/theme'
    | '/api/frontend-lib/theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/generate-theme'
    | '/api/google-fonts'
    | '/editor/theme'
    | '/api/frontend-lib/theme'
  id:
    | '__root__'
    | '/api/generate-theme'
    | '/api/google-fonts'
    | '/editor/theme'
    | '/api/frontend-lib/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiGenerateThemeRoute: typeof ApiGenerateThemeRoute
  ApiGoogleFontsRoute: typeof ApiGoogleFontsRoute
  EditorThemeRoute: typeof EditorThemeRoute
  ApiFrontendLibThemeRoute: typeof ApiFrontendLibThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor/theme': {
      id: '/editor/theme'
      path: '/editor/theme'
      fullPath: '/editor/theme'
      preLoaderRoute: typeof EditorThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-fonts': {
      id: '/api/google-fonts'
      path: '/api/google-fonts'
      fullPath: '/api/google-fonts'
      preLoaderRoute: typeof ApiGoogleFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-theme': {
      id: '/api/generate-theme'
      path: '/api/generate-theme'
      fullPath: '/api/generate-theme'
      preLoaderRoute: typeof ApiGenerateThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frontend-lib/theme': {
      id: '/api/frontend-lib/theme'
      path: '/api/frontend-lib/theme'
      fullPath: '/api/frontend-lib/theme'
      preLoaderRoute: typeof ApiFrontendLibThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiGenerateThemeRoute: ApiGenerateThemeRoute,
  ApiGoogleFontsRoute: ApiGoogleFontsRoute,
  EditorThemeRoute: EditorThemeRoute,
  ApiFrontendLibThemeRoute: ApiFrontendLibThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
